### ISSUE TITLE
Property 'assign' does not exist on type 'ObjectConstructor'

### ISSUE THREAD

**Issue by chriseenberg** [surmon-china/ng2-quill-editor#1]
Hi.

I've just downloaded your component and im trying to make it work. I've added the component to my appModule as explained in the ReadMe file, then i get this error: 

../angular-seed/angular-webpack/node_modules/ng2-quill-editor/quillEditor.component.ts:81:57 
Property 'assign' does not exist on type 'ObjectConstructor'.

i also get a bunch of other errors, like this one: 
Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (eval at <anonymous> (http://localhost:8081/vendor.js:95:2)

Most of the errors occur in the vendor.ts file.

I had to set the ` "noImplicitAny": false` to false to avoid a whole bunch of other errors regarding implicitly type any.

Is there any fix to these errors? Am i missing something?

I'm running with typescript version 2.0.10 - angular version ~2.2.0

Kind regards Chris

**Comment by surmon-china** [comment]
The problem is caused by the babel is not configured, please refer to here.

http://stackoverflow.com/questions/35959372/property-assign-does-not-exist-on-type-objectconstructor
