### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by ntclark4** [surmon-china/ng2-quill-editor#4]
I am running an Angular 2 app inside an MVC.NET app following these instruction: http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/. I have successfully added ng2-quill-editor to my project and even linked to it in app.module.ts. But when I follow the instructions to add a third-party library in the link above, I get this error in the console from webpack: 
_command:_ webpack --config webpack.config.vendor.js
_output:_ Module not found: Error: Cannot resolve module 'ng2-quill-editor'

I have not had this problem with other third-party packages. Any idea what's wrong?

Thanks

**Comment by surmon-china** [comment]
v2.0.0 will fix it.

**Comment by Silvercast** [comment]
I still get this issue

**Comment by jfaquinojr** [comment]
still getting this error

$ webpack --config webpack.config.vendor.js
ERROR in dll vendor
Module not found: Error: Can't resolve 'ngx-quill-editor'

dotnet new angular
